name: Publish to PyPI
on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install build
        run: >-
          python -m
          pip install build --user
      - name: Build a source tarball
        run: >-
          python -m
          build --sdist --outdir dist/ .
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      # Uncomment when there's something worth of releasing
      #- name: Generate changelog
      #  run: |
      #    version=${GITHUB_REF#refs/tags/v}
      #    sed "0,/^## \\[\\?${version//./\\.}/d;/^## /,\$d" CHANGELOG.md > ${{ github.workspace }}-CHANGELOG.txt
      #    echo "name=HALO reader $version" >> $GITHUB_OUTPUT
      #  id: changelog
      #- name: Create release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    name: ${{ steps.changelog.outputs.name }}
      #    body_path: ${{ github.workspace }}-CHANGELOG.txt
